version: '3.2'

services:
  app:
    image: "istio-prometheus-exporter"
    restart: always
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: "*"
      ISTIO_PILOT_ADDRESS: http://127.0.0.1:8081 # kubectl --namespace=istio-system port-forward <pod> 8081:8080
    ports:
      - 8080:8080
